# Generated by Django 4.0 on 2022-01-13 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_feedback_user_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.technician'),
        ),
    ]
