# Generated by Django 4.0 on 2022-01-14 21:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
