# Generated by Django 4.0 on 2022-01-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_technician_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paymentOrder', to='users.user'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.IntegerField(max_length=300),
        ),
    ]
